<?php

namespace AppBundle\Repository;

/**
 * CategoriaPublicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaPublicaRepository extends \Doctrine\ORM\EntityRepository
{
}
