<?php

namespace AppBundle\Repository;

/**
 * CategoriaPrivadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaPrivadaRepository extends \Doctrine\ORM\EntityRepository
{
}
