<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Evaluador;

/**
 * CriterioPremioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterioPremioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNoAsociadosAEvaluador(Evaluador $evaluador)
	{
		$qb = $this->createQueryBuilder('cp');
		$qb ->where('cp.id NOT IN (SELECT IDENTITY(ecp.criterioPremio) FROM AppBundle:EvaluadorCriterioPremio ecp WHERE ecp.evaluador = :evaluador)')
			->orderBy('cp.orden')
			->setParameter('evaluador', $evaluador);

		return $qb->getQuery()->getResult();
	}
}
