<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Premio;

/**
 * EquipoEvaluadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoEvaluadorRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEquiposDelPremioQb(Premio $premio)
	{
		return $this->createQueryBuilder('ee')
			->andWhere('ee.premio = :premio')
			->setParameter('premio', $premio);
	}

	public function getEquiposDelPremio(Premio $premio)
	{
		$qb = $this->getEquiposDelPremioQb($premio);

		return $qb->getQuery()->getResult();
	}
}
