<?php

namespace AppBundle\Repository;

/**
 * EvaluadorTrabajoActualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorTrabajoActualRepository extends \Doctrine\ORM\EntityRepository
{
}
