<?php

namespace AppBundle\Repository;

/**
 * EvaluadorCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
