<?php

namespace AppBundle\Repository;

/**
 * EvaluadorEstudioUniversitarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorEstudioUniversitarioRepository extends \Doctrine\ORM\EntityRepository
{
}
