<?php

namespace AppBundle\Repository;

/**
 * EvaluadorConSeCurDictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorConSeCurDictRepository extends \Doctrine\ORM\EntityRepository
{
}
