<?php

namespace AppBundle\Repository;

/**
 * EvaluadorTrabajoIndependienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorTrabajoIndependienteRepository extends \Doctrine\ORM\EntityRepository
{
}
