<?php

namespace AppBundle\Repository;

/**
 * EvaluadorTrabajoDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorTrabajoDocenteRepository extends \Doctrine\ORM\EntityRepository
{
}
