<?php

namespace AppBundle\Repository;

/**
 * EvaluadorEstudioPosgradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorEstudioPosgradoRepository extends \Doctrine\ORM\EntityRepository
{
}
