<?php

namespace AppBundle\Repository;

/**
 * EvaluadorCriterioPremioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorCriterioPremioRepository extends \Doctrine\ORM\EntityRepository
{
}
