<?php

namespace AppBundle\Repository;

/**
 * EvaluadorTrabajoEstatalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorTrabajoEstatalRepository extends \Doctrine\ORM\EntityRepository
{
}
