<?php

namespace AppBundle\Repository;

/**
 * EvaluadorTrabajoEmpPrivadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorTrabajoEmpPrivadaRepository extends \Doctrine\ORM\EntityRepository
{
}
