<?php

namespace AppBundle\Repository;

/**
 * EvaluadorExpGestionCalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorExpGestionCalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
