<?php

namespace AppBundle\Repository;

/**
 * EvaluadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorRepository extends \Doctrine\ORM\EntityRepository
{
}
