<?php

namespace AppBundle\Repository;

/**
 * EvaluadorTrabajoOngRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorTrabajoOngRepository extends \Doctrine\ORM\EntityRepository
{
}
