<?php

namespace AppBundle\Repository;

/**
 * FormularioEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
