<?php

namespace AppBundle\Repository;

/**
 * FormularioEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioEvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
}
