<?php

namespace AppBundle\Repository;

/**
 * FormularioEvaluadorPremioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioEvaluadorPremioRepository extends \Doctrine\ORM\EntityRepository
{
}
