<?php

namespace AppBundle\Repository;

/**
 * OrganizacionPublicaClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
