<?php

namespace AppBundle\Repository;


/**
 * OrganizacionPublicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionPublicaRepository extends \Doctrine\ORM\EntityRepository
{
}
