<?php

namespace AppBundle\Repository;

/**
 * OrganizacionPublicaPresupuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionPublicaPresupuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
