<?php

namespace AppBundle\Repository;

/**
 * OrganizacionPublicaProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionProveedorRepository extends \Doctrine\ORM\EntityRepository
{
}
