<?php

namespace AppBundle\Repository;

/**
 * OrganizacionPrivadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionPrivadaRepository extends \Doctrine\ORM\EntityRepository
{
}
