<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Premio;


/**
 * OrganizacionPublicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionPublicaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCant(Premio $premio){
		$qb = $this->createQueryBuilder('op')
			->select('count(op.id)')
			->andWhere('op.premio = :premio')
            ->setParameter('premio', $premio);

		return  $qb->getQuery()->getSingleScalarResult();
	}
}
