<?php

namespace AppBundle\Repository;

/**
 * OrganizacionPremioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionPremioRepository extends \Doctrine\ORM\EntityRepository
{
}
