<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EquipoEvaluador;
use AppBundle\Entity\Premio;
use AppBundle\Entity\Organizacion;

/**
 * OrganizacionPrivadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getQBForEquipoEvaluadorType(EquipoEvaluador $ee)
	{
		$qb = $this->createQueryBuilder('o')
            ->andWhere('o.premio = :premio')
            ->andWhere('o.id NOT IN (SELECT IDENTITY(ee.organizacion) FROM AppBundle:EquipoEvaluador ee WHERE ee.premio = :eepremio)')
            ->setParameter('premio', $ee->getPremio())
            ->setParameter('eepremio', $ee->getPremio())
        ;

        if ($ee->getId()) {
            $qb->orWhere('o = :organizacion')
                ->setParameter('organizacion', $ee->getOrganizacion());
        }

        return $qb;
	}

    public function getOrganizacionesActivasDelPremio(Premio $premio)
    {
        $qb = $this->createQueryBuilder('o')
            ->andWhere('o.premio = :premio')
            ->andWhere('o.estado = :estado')
            ->andWhere('o.id NOT IN (SELECT IDENTITY(ee.organizacion) FROM AppBundle:EquipoEvaluador ee WHERE ee.premio = :eepremio)')
            ->setParameter('premio', $premio)
            ->setParameter('eepremio', $premio)
            ->setParameter('estado', Organizacion::ESTADO_ACTIVO);

        return $qb->getQuery()->getResult();
    }
}
