<?php

namespace AppBundle\Repository;

/**
 * PremioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PremioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getActual()
	{
		$anioActual = date('Y');

		return $this->createQueryBuilder('p')
			->where('p.anio = :anioActual')
			->setParameter('anioActual', $anioActual)
			->getQuery()
			->getOneOrNullResult();
	}
}
