<?php

namespace AppBundle\Repository;

/**
 * RespuestasEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestasEvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
}
