<?php

namespace AppBundle\Repository;

/**
 * RespuestaEvaluacionEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestaEvaluacionEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
