<?php

namespace AppBundle\Repository;

/**
 * TituloUniversitarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TituloUniversitarioRepository extends \Doctrine\ORM\EntityRepository
{
}
