app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/profile"

fos_user_ressetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/resetting"

fos_user_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/profile"
