<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormularioEvaluacion extends \AppBundle\Entity\FormularioEvaluacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'version', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'criteriosEvaluacion', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'evaluadorPremioFormularios', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'equipoFormularios', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'premios', 'createdAt', 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'createdBy', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'updatedBy'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'version', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'criteriosEvaluacion', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'evaluadorPremioFormularios', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'equipoFormularios', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'premios', 'createdAt', 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'createdBy', '' . "\0" . 'AppBundle\\Entity\\FormularioEvaluacion' . "\0" . 'updatedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormularioEvaluacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function addCriteriosEvaluacion(\AppBundle\Entity\CriterioEvaluacion $criterioEvaluacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCriteriosEvaluacion', [$criterioEvaluacion]);

        return parent::addCriteriosEvaluacion($criterioEvaluacion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCriteriosEvaluacion(\AppBundle\Entity\CriterioEvaluacion $criterioEvaluacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCriteriosEvaluacion', [$criterioEvaluacion]);

        return parent::removeCriteriosEvaluacion($criterioEvaluacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriteriosEvaluacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriteriosEvaluacion', []);

        return parent::getCriteriosEvaluacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getCriteriosEvaluacionRaiz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriteriosEvaluacionRaiz', []);

        return parent::getCriteriosEvaluacionRaiz();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addPremio(\AppBundle\Entity\Premio $premio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPremio', [$premio]);

        return parent::addPremio($premio);
    }

    /**
     * {@inheritDoc}
     */
    public function removePremio(\AppBundle\Entity\Premio $premio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePremio', [$premio]);

        return parent::removePremio($premio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremios', []);

        return parent::getPremios();
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntajeMaximo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntajeMaximo', []);

        return parent::getPuntajeMaximo();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvaluadorPremioFormulario(\AppBundle\Entity\FormularioEvaluadorPremio $evaluadorPremioFormulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvaluadorPremioFormulario', [$evaluadorPremioFormulario]);

        return parent::addEvaluadorPremioFormulario($evaluadorPremioFormulario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvaluadorPremioFormulario(\AppBundle\Entity\FormularioEvaluadorPremio $evaluadorPremioFormulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvaluadorPremioFormulario', [$evaluadorPremioFormulario]);

        return parent::removeEvaluadorPremioFormulario($evaluadorPremioFormulario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluadorPremioFormularios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluadorPremioFormularios', []);

        return parent::getEvaluadorPremioFormularios();
    }

    /**
     * {@inheritDoc}
     */
    public function addEquipoFormulario(\AppBundle\Entity\FormularioEquipo $equipoFormulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEquipoFormulario', [$equipoFormulario]);

        return parent::addEquipoFormulario($equipoFormulario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEquipoFormulario(\AppBundle\Entity\FormularioEquipo $equipoFormulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEquipoFormulario', [$equipoFormulario]);

        return parent::removeEquipoFormulario($equipoFormulario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipoFormularios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipoFormularios', []);

        return parent::getEquipoFormularios();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\AppBundle\Entity\Usuario $createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(\AppBundle\Entity\Usuario $updatedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

}
